"use client"

import { useEffect, useRef } from "react"
import { useSearchParams } from "next/navigation"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { ActionsPageHeader } from "@/components/actions/ActionsPageHeader"
import { ActionCard } from "@/components/actions/ActionCard"
import {
  ACTIONS_QUERY_KEY,
  LIVE_REFRESH_INTERVAL_MS,
  fetchActions,
} from "@/lib/client/dashboard-queries"
import { useLiveRefetch } from "@/lib/client/use-live-refetch"
import type {
  ActionsViewState,
  PendingAction,
  DraftEmailPayload,
  RescheduleMeetingPayload,
} from "@/types"

async function approveAction(id: string) {
  const res = await fetch(`/api/actions/${id}/approve`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({}),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.error ?? "Failed to approve")
  }
  return res.json() as Promise<PendingAction>
}

async function rejectAction(id: string) {
  const res = await fetch(`/api/actions/${id}/reject`, {
    method: "POST",
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.error ?? "Failed to reject")
  }
  return res.json() as Promise<PendingAction>
}

async function editAction(id: string, content: DraftEmailPayload | RescheduleMeetingPayload) {
  const res = await fetch(`/api/actions/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ content }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.error ?? "Failed to update")
  }
  return res.json() as Promise<PendingAction>
}

async function generateDraft(id: string, force = false) {
  const res = await fetch(`/api/actions/${id}/draft`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ force }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.error ?? "Failed to generate draft")
  }
  return res.json() as Promise<PendingAction>
}

export default function ActionsPage() {
  const searchParams = useSearchParams()
  const queryClient = useQueryClient()
  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: ACTIONS_QUERY_KEY,
    queryFn: fetchActions,
    staleTime: 10000,
    refetchInterval: LIVE_REFRESH_INTERVAL_MS,
    refetchIntervalInBackground: true,
    refetchOnWindowFocus: true,
    refetchOnMount: "always",
  })
  useLiveRefetch(refetch)
  const actions = data?.actions ?? []
  const focusedActionId = searchParams.get("focus")
  const autoEnterEdit = searchParams.get("compose") === "1"
  const autoGenerateDraftForFocus = searchParams.get("compose") === "1"

  const focusedAction = focusedActionId
    ? actions.find((a) => a.id === focusedActionId)
    : null
  const draftPayload =
    focusedAction?.type === "draft_email"
      ? (focusedAction.reviewedContent ?? focusedAction.proposedAction) as DraftEmailPayload | undefined
      : undefined
  const shouldAutoGenerateDraft =
    autoGenerateDraftForFocus &&
    focusedAction?.type === "draft_email" &&
    focusedAction?.status === "pending" &&
    !draftPayload?.body?.trim()

  const viewState = data?.viewState ?? {
    source: "mock" as const,
    statusNote: "Relay is showing explicit demo fallback actions.",
  }

  const approveMutation = useMutation({
    mutationFn: approveAction,
    onSuccess: (_, approvedId) => {
      queryClient.setQueryData(
        ACTIONS_QUERY_KEY,
        (current: { actions: PendingAction[]; displayName: string | null; viewState: ActionsViewState } | undefined) =>
          current
            ? { ...current, actions: current.actions.filter((a) => a.id !== approvedId) }
            : current
      )
      queryClient.invalidateQueries({ queryKey: ACTIONS_QUERY_KEY })
    },
  })
  const rejectMutation = useMutation({
    mutationFn: rejectAction,
    onSuccess: (_, rejectedId) => {
      queryClient.setQueryData(
        ACTIONS_QUERY_KEY,
        (current: { actions: PendingAction[]; displayName: string | null; viewState: ActionsViewState } | undefined) =>
          current
            ? { ...current, actions: current.actions.filter((a) => a.id !== rejectedId) }
            : current
      )
      queryClient.invalidateQueries({ queryKey: ACTIONS_QUERY_KEY })
    },
  })
  const editMutation = useMutation({
    mutationFn: ({ id, content }: { id: string; content: DraftEmailPayload | RescheduleMeetingPayload }) =>
      editAction(id, content),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ACTIONS_QUERY_KEY }),
  })
  const generateDraftMutation = useMutation({
    mutationFn: ({ id, force }: { id: string; force?: boolean }) => generateDraft(id, force),
    onSuccess: (updatedAction) => {
      queryClient.setQueryData(
        ACTIONS_QUERY_KEY,
        (current: {
          actions: PendingAction[]
          displayName: string | null
          viewState: ActionsViewState
        } | undefined) =>
          current
            ? {
                ...current,
                actions: current.actions.map((action) =>
                  action.id === updatedAction.id ? updatedAction : action
                ),
              }
            : current
      )
    },
  })

  const hasAutoGeneratedForFocus = useRef(false)
  useEffect(() => {
    if (!shouldAutoGenerateDraft || !focusedActionId || hasAutoGeneratedForFocus.current) return
    hasAutoGeneratedForFocus.current = true
    generateDraftMutation.mutate({ id: focusedActionId })
    // eslint-disable-next-line react-hooks/exhaustive-deps -- only run once when landing from briefing with compose=1
  }, [focusedActionId, shouldAutoGenerateDraft])

  const pendingActions = actions.filter((a) => a.status === "pending")
  const urgentCount = pendingActions.filter((a) => a.urgency === "urgent").length
  const conflictCount = pendingActions.filter((a) => a.type === "reschedule_meeting").length
  const orderedActions = focusedActionId
    ? [...actions].sort((left, right) => {
        if (left.id === focusedActionId) return -1
        if (right.id === focusedActionId) return 1
        return 0
      })
    : actions

  if (isLoading) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="h-8 w-8 animate-spin rounded-full border-2 border-[#213443] border-t-transparent" />
          <p className="text-sm text-[#3F5363]">Loading actions...</p>
        </div>
      </div>
    )
  }

  if (isError) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <div className="rounded-relay-card border border-[#3F5363]/25 bg-white/80 p-5 text-center max-w-md shadow-relay-soft">
          <p className="font-medium text-[#1B2E3B]">Something went wrong</p>
          <p className="mt-1 text-sm text-[#3F5363]">
            {error instanceof Error ? error.message : "Failed to load actions"}
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="animate-relay-fade-in">
        <ActionsPageHeader
          pendingCount={pendingActions.length}
          urgentCount={urgentCount}
          conflictCount={conflictCount}
          sourceLabel={viewState.source === "google" ? "Live Actions" : "Demo Actions"}
          statusNote={viewState.statusNote}
        />
      </div>
      <div className="space-y-4 animate-relay-fade-in opacity-0 [animation-delay:75ms] [animation-fill-mode:forwards]">
        {actions.length === 0 ? (
          <div className="rounded-relay-card bg-white/80 backdrop-blur-sm border border-[var(--border)] p-8 text-center shadow-relay-soft">
            <p className="text-[#3F5363]">No actions to review</p>
          </div>
        ) : (
          orderedActions.map((action) => (
            <ActionCard
              key={action.id}
              action={action}
              onApprove={(id) => approveMutation.mutate(id)}
              onReject={(id) => rejectMutation.mutate(id)}
              onEditContent={(id, content) => editMutation.mutate({ id, content })}
              onGenerateDraft={(id) => generateDraftMutation.mutate({ id })}
              onRegenerateDraft={(id) => generateDraftMutation.mutate({ id, force: true })}
              isApproving={approveMutation.isPending && approveMutation.variables === action.id}
              isRejecting={rejectMutation.isPending && rejectMutation.variables === action.id}
              isGeneratingDraft={
                generateDraftMutation.isPending && generateDraftMutation.variables?.id === action.id
              }
              isFocused={focusedActionId === action.id}
              autoEnterEdit={focusedActionId === action.id && autoEnterEdit}
            />
          ))
        )}
      </div>
    </div>
  )
}
